version: '3.8'

services:
  mockserver:
    image: mockserver/mockserver
    platform: linux/amd64
    container_name: mockserver
#    network_mode: "host"
    ports:
      - "0.0.0.0:1080:1080"
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/expectations.json
    volumes:
      - ./config:/config
