# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      is_key_content_base64: true
    )

    match(
      type: "appstore",
      readonly: true,
      api_key: api_key
    )

    build_app(
      scheme: "Fastbreak",
      export_method: "app-store",
      xcargs: "CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER='match AppStore com.joebad.fastbreak' CODE_SIGN_IDENTITY='iPhone Distribution'",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.joebad.fastbreak" => "match AppStore com.joebad.fastbreak"
        }
      }
    )

    upload_to_testflight(api_key: api_key)
  end
end
