source "https://rubygems.org"

gem "xcodeproj", git: "https://github.com/sprzenus/Xcodeproj.git", branch: "fix_issue_996_xcode16"
gem "fastlane"
gem "cocoapods"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
