# fly.toml app configuration file generated for fastbreak-api on 2025-08-01T22:41:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastbreak-api'
primary_region = 'iad'

[build]

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ASPNETCORE_URLS = 'http://*:8085'

[http_service]
  internal_port = 8085
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.checks]
    [http_service.checks.alive]
      type = "http"
      interval = "15s"
      timeout = "10s"
      grace_period = "30s"
      method = "GET"
      path = "/"
      protocol = "http"
      tls_skip_verify = false

    [http_service.checks.readiness]
      type = "http"
      interval = "30s"  
      timeout = "10s"
      grace_period = "45s"
      method = "GET"
      path = "/"
      protocol = "http"
      tls_skip_verify = false

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096
