name: Deploy API and Build KMP

on:
  push:
    branches:
      - main

jobs:
  build-kmp:
    name: Build KMP
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Generate build info
        id: build_info
        run: |
          echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
          echo "build_number=${{ github.run_number }}" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Writing to gradle.properties
        run: |
          cat > kmp/local.properties << EOF
          GOOGLE_AUTH_SERVER_ID=${{ secrets.GOOGLE_AUTH_SERVER_ID }}
          EOF

      - name: Configure signing properties
        run: |
          cat >> kmp/gradle.properties << EOF
          
          # Release signing configuration (from CI secrets)
          RELEASE_STORE_FILE=../keystore.jks
          RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}
          EOF

      - name: Create keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > kmp/keystore.jks

      - name: Build Android APK
        run: |
          cd kmp
          ./gradlew :androidApp:assembleRelease --no-daemon

      - name: Create artifact archive
        run: |
          mkdir -p artifacts
          cp kmp/androidApp/build/outputs/apk/release/*.apk artifacts/ || true
          cp kmp/shared/build/libs/*.jar artifacts/ || true
          
          # Create build info file
          echo "Build Number: ${{ steps.build_info.outputs.build_number }}" > artifacts/build_info.txt
          echo "Timestamp: ${{ steps.build_info.outputs.timestamp }}" >> artifacts/build_info.txt
          echo "Commit: ${{ steps.build_info.outputs.short_sha }}" >> artifacts/build_info.txt
          echo "Branch: ${{ github.ref_name }}" >> artifacts/build_info.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fastbreak-kmp-${{ steps.build_info.outputs.timestamp }}-build${{ steps.build_info.outputs.build_number }}
          path: artifacts/
          retention-days: 30       