name: Deploy API and Build KMP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    env:
      MONGO_IP: ${{ secrets.MONGO_IP }}
      MONGO_DB: ${{ secrets.MONGO_DB }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASS: ${{ secrets.MONGO_PASS }}
      ENABLE_SCHEDULE_PULLER: 1
      ENABLE_DAILY_JOB: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_MONGO_IP: ${{ secrets.MONGO_IP }}
          envkey_MONGO_DB: ${{ secrets.MONGO_DB }}
          envkey_MONGO_USER: ${{ secrets.MONGO_USER }}
          envkey_MONGO_PASS: ${{ secrets.MONGO_PASS }}
          envkey_ENABLE_SCHEDULE_PULLER: 1
          envkey_ENABLE_DAILY_JOB: 1
          directory: api

      - name: Deploy to Fly.io
        run: |
          cd api
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          